name: Deploy Node.js to Elastic Beanstalk

on:
  push:
    branches:
      - main   # or 'master' if that’s your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Package app
        run: zip -r app.zip . -x '*.git*'

      - name: Get Node.js version from package.json
        id: node_version
        run: |
          VERSION=$(jq -r '.engines.node' package.json)
          # Remove ^ or ~ if present
          VERSION_CLEAN=${VERSION#\^}
          VERSION_CLEAN=${VERSION_CLEAN#\~}
          echo "NODE_VERSION=$VERSION_CLEAN" >> $GITHUB_ENV
          echo "Node.js version from package.json: $VERSION_CLEAN"

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          EB_APPLICATION_NAME: ${{ secrets.EB_APPLICATION_NAME }}
          EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENVIRONMENT_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NODE_VERSION: ${{ env.NODE_VERSION }}
        run: |
          VERSION_LABEL="v-${{ github.run_number }}"
          echo "Deploying version: $VERSION_LABEL to environment: $EB_ENVIRONMENT_NAME"

          # Configure AWS CLI
          aws configure set region $AWS_REGION
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

          # Check if the environment exists
          ENV_CHECK=$(aws elasticbeanstalk describe-environments \
            --application-name "$EB_APPLICATION_NAME" \
            --environment-names "$EB_ENVIRONMENT_NAME" \
            --query "Environments[0].EnvironmentName" \
            --output text)

          if [ "$ENV_CHECK" = "None" ] || [ -z "$ENV_CHECK" ]; then
            echo "Environment does not exist. Creating $EB_ENVIRONMENT_NAME..."
            aws elasticbeanstalk create-environment \
              --application-name "$EB_APPLICATION_NAME" \
              --environment-name "$EB_ENVIRONMENT_NAME" \
              --solution-stack-name "64bit Amazon Linux 2023 v6.6.3 running Node.js 22" \
              --version-label "$VERSION_LABEL"
            echo "Environment creation started. Waiting for it to be ready..."
            aws elasticbeanstalk wait environment-ready \
              --environment-names "$EB_ENVIRONMENT_NAME"
          fi

          # Create application version (if it doesn’t exist)
          aws elasticbeanstalk create-application-version \
            --application-name "$EB_APPLICATION_NAME" \
            --version-label "$VERSION_LABEL" \
            --source-bundle S3Bucket="elasticbeanstalk-$AWS_REGION-$AWS_ACCOUNT_ID",S3Key="app.zip" || true

          # Update environment to new version
          aws elasticbeanstalk update-environment \
            --environment-name "$EB_ENVIRONMENT_NAME" \
            --version-label "$VERSION_LABEL"

