name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main   # deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Zip application (without node_modules)
        run: zip -r app.zip . -x "*.git*" -x "node_modules/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload app.zip to S3
        run: |
          aws s3 cp app.zip s3://elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}/app.zip

      - name: Get current EB version
        id: current_version
        run: |
          CURRENT_VERSION=$(aws elasticbeanstalk describe-environments \
            --environment-names "${{ secrets.EB_ENV_NAME }}" \
            --query "Environments[0].VersionLabel" --output text)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
          echo "Current EB version: $CURRENT_VERSION"

      - name: Create new EB application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "v-${{ github.run_number }}" \
            --source-bundle S3Bucket="elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}",S3Key="app.zip"

      - name: Deploy new version to EB environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "v-${{ github.run_number }}"

      - name: Rollback if deploy fails (optional)
        if: failure()
        run: |
          echo "Deployment failed! Rolling back to $CURRENT_VERSION"
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --version-label "$CURRENT_VERSION"

